import { defineField, defineType } from "sanity";

export const producer = defineType({
  name: "producer",
  title: "Producer",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "displayName",
      title: "Display Name",
      type: "string",
      description: "Optional longer or bilingual name, for example Kellerei Girlan / Cantina Girlan.",
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "string",
      initialValue: "Italy",
    }),
    defineField({
      name: "heroImage",
      title: "Producer Photo",
      type: "image",
      options: { hotspot: true },
      fields: [
        defineField({
          name: "alt",
          title: "Alt Text",
          type: "string",
          description: "Short description for accessibility and future exports.",
        }),
      ],
    }),
    defineField({
      name: "region",
      title: "Region",
      type: "reference",
      to: [{ type: "region" }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "subregionOrArea",
      title: "Subregion / Area",
      type: "string",
    }),
    defineField({
      name: "villageOrTown",
      title: "Village / Town",
      type: "string",
    }),
    defineField({
      name: "producerType",
      title: "Producer Type",
      type: "string",
      options: {
        list: ["Cooperative", "Family estate", "Historic estate", "Small grower", "Merchant / negociant", "Monastic estate"],
      },
    }),
    defineField({
      name: "northboundRelationship",
      title: "Northbound Relationship",
      type: "string",
      options: {
        list: ["Represented producer", "Producer we like", "Producer of interest", "Reference producer", "Directory listing only"],
      },
    }),
    defineField({
      name: "bestKnownFor",
      title: "Best Known For",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "strongestWineStyles",
      title: "Strongest Wine Styles",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "bestFor",
      title: "Best For",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "priceLevel",
      title: "Price Level",
      type: "string",
      options: {
        list: ["Entry", "Moderate", "Medium-high", "Premium", "Luxury"],
      },
    }),
    defineField({
      name: "visitDifficulty",
      title: "Visit Difficulty",
      type: "string",
      options: {
        list: ["Easy", "Moderate", "Appointment essential", "Difficult / limited access"],
      },
    }),
    defineField({
      name: "tastingExperienceTypes",
      title: "Tasting Experience Types",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "familyFriendly",
      title: "Family Friendly",
      type: "string",
      options: {
        list: ["Yes", "Maybe", "Not ideal", "Unknown"],
      },
    }),
    defineField({
      name: "languages",
      title: "Languages",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "appointmentRequired",
      title: "Appointment Required",
      type: "string",
      options: {
        list: ["Usually", "Recommended", "Required", "Walk-ins possible", "Unknown"],
      },
    }),
    defineField({
      name: "grapes",
      title: "Grapes",
      type: "array",
      of: [{ type: "reference", to: [{ type: "grape" }] }],
    }),
    defineField({
      name: "nearbyProducers",
      title: "Nearby Producers",
      type: "array",
      of: [{ type: "reference", to: [{ type: "producer" }] }],
    }),
    defineField({
      name: "overview",
      title: "Short Overview",
      type: "text",
      rows: 6,
    }),
    defineField({
      name: "whyVisit",
      title: "Why Visit",
      type: "text",
      rows: 4,
    }),
    defineField({
      name: "aboutProducer",
      title: "About the Producer",
      type: "text",
      rows: 8,
    }),
    defineField({
      name: "placeAndVineyards",
      title: "Place & Vineyards",
      type: "text",
      rows: 8,
    }),
    defineField({
      name: "winemakingPhilosophy",
      title: "Winemaking & Philosophy",
      type: "text",
      rows: 8,
    }),
    defineField({
      name: "wineStyle",
      title: "What the Wines Feel Like",
      type: "text",
      rows: 8,
    }),
    defineField({
      name: "keyWinesOverview",
      title: "Key Wines",
      type: "text",
      rows: 6,
      description: "Narrative overview of important wines. Use linked Wine objects for bottle-level detail.",
    }),
    defineField({
      name: "bestValue",
      title: "Best Value",
      type: "text",
      rows: 5,
    }),
    defineField({
      name: "whatWeWouldBuy",
      title: "What We Would Buy",
      type: "text",
      rows: 5,
    }),
    defineField({
      name: "travelExperience",
      title: "Travel Experience",
      type: "text",
      rows: 8,
    }),
    defineField({
      name: "lessIdealFor",
      title: "Less Ideal For",
      type: "text",
      rows: 5,
    }),
    defineField({
      name: "northboundPerspective",
      title: "Northbound Perspective",
      type: "text",
      rows: 6,
    }),
    defineField({
      name: "styleAndPhilosophy",
      title: "Legacy Style and Philosophy",
      type: "text",
      rows: 4,
      hidden: true,
    }),
    defineField({
      name: "atmosphere",
      title: "Legacy Visit Atmosphere",
      type: "text",
      rows: 3,
      hidden: true,
    }),
    defineField({
      name: "knownFor",
      title: "Legacy Known For",
      type: "text",
      rows: 3,
      hidden: true,
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "region.title",
    },
  },
});
